# Use Nginx as the base image
FROM nginx:alpine

# Copy Angular build files to the Nginx web directory
COPY dist /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
